### ISSUE TITLE
Data balancing

### ISSUE THREAD

**Issue by IliaMarek** [tomyitav/datahack-2018-challenge#1]
The data is very unbalanced -  only ~25% of users are "churned"
This issue must be addressed in a training process.
Possible solution is passing **class_weight='balanced'** parameter to the classification model.
Not sure if all models have this parameter (SVM has it).

**Comment by tomyitav** [comment]
I think we should take a look at this [library](https://github.com/scikit-learn-contrib/imbalanced-learn).
It is more challenging to deal with the current sklearn NN classifier.
